### ISSUE TITLE
将应用程式翻译成汉语 / translate app into mandarin chinese

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#46]
### Expected Behavior

Chinese Mandarin speakers can use the application in mandarin chinese language.

### Task

All translations are located in https://github.com/mirai-audio/mir/tree/master/app/locales, with directory for each translation language. 

These should be added under a new `zh-cn` directory in `app/locales` according to the `ISO 639-3` standard names.

Please use English as the source for translations, as it contains a complete list of up-to-date strings.

Please use our [Writing Styleguide](https://github.com/mirai-audio/mir/wiki/Writing-Styleguide) for how the voice & persona of the text should come across.

**Comment by pallymore** [comment]
I can work on this one.
