### ISSUE TITLE
translate app into español / traducir aplicación en español

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#47]
### Expected Behavior

Spanish speakers can use the application en español.

### Task

All translations are located in https://github.com/mirai-audio/mir/tree/master/app/locales, with directory for each translation language. 

These should be added under a new `es` directory in `app/locales` according to the `ISO 639-1` standard names.

Please use English as the source for translations, as it contains a complete list of up-to-date strings.

Please use our [Writing Styleguide](https://github.com/mirai-audio/mir/wiki/Writing-Styleguide) for how the voice & persona of the text should come across.

**Comment by andresluna11** [comment]
I can translate it to spanish, I am spanish

**Comment by 0xadada** [comment]
@andresluna11 go for it!

Could you open a single PR for all translation files?

What country Spanish are you writing, Spain (es-es), es-MX (Mexico)?

**Comment by juanluischaurant** [comment]
I would like to help you, @andresluna11 
I'm from Venezuela (es-ve)

**Comment by 0xadada** [comment]
@juanluischaurant if you contribute, please contribute a new folder `es-ve` to the branch @andresluna11 is working on `andresluna11:patch-1`.

**Comment by juanluischaurant** [comment]
Perfect!
So, I'll translate these two files


* about.js
*  app.js

**Comment by EnrikeGonzaloLegarra** [comment]
I translated it into Spanish, but I can not upload it

**Comment by 0xadada** [comment]
@EnrikeGonzaloLegarra why?

**Comment by EnrikeGonzaloLegarra** [comment]
I have this error:
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by EnrikeGonzaloLegarra** [comment]
I can´t do git push

**Comment by 0xadada** [comment]
You are trying to push to _my_ repo, but you need to
1) fork the repo
2) clone your fork
3) make the changes on your fork
4) push to your fork
5) open a PR to my repo 🎉
